dist: xenial
sudo: required
language: java
jdk:
- openjdk8
- openjdk11
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - PULL_REQUEST=${TRAVIS_PULL_REQUEST}
  - TAG=${TRAVIS_TAG:-latest}
  - BRANCH=${TRAVIS_BRANCH:-master}
  - secure: ZUtBG8nQ3n7r434wrNnkSSMwpqG8Bdqv/nUubP7RPAtGIS/qyWOtYsNLyAj1jKpS5NR0xuqMBSX6BJd8JbG11gpTYH4Gx4aE+TmnhFm489IgywLeEKrlU+5m26I4kMw/P/JoK1jJ6Juu9TyLMLtzkzJhYK1n/VVS1kq2LRXn81ukJrhbxGIqNvk6ok46s0L8SWwjFVyBPgzxc6kcjOQSn9y/zrKsSZUVi6dW0Q7oGTfIMq6LIIlQWk3LJPMW4g8QH6+67WI4z9Ef8z5lzcJ5ypi0tDO9uCiGAGhh61mDdlMJqJNtVDCZz/ofwBRn0ZhAHaT0vGwf78hH/XIUJEQUVKIBndS0QrrIfazhYIVyBMikZI2fFUzXDOtQ21iIWDkcrJowAsaMJzXIzGrjVSc+4rBbhFJV7zlrT0uIPjuQeY0MbyP87qGn2kocIHKtEQWGaqLgUuJO/T4K9ACQvoa+VhgJpAunZ0EwQzZA/4h3qMMveYdHQaWHlbU4xJyOOyS7nGPF/Nm0ZweG8bYOgHUjqBl7LO+AvxXNKRqlrz2PHtRGHSy/j6PnUDZT1cbOaWd7rggfO1hkw39RGc1Gg1xOji/0Jv1MmOXO2GnmkwzWWTL8tOCXI3Yh+v5pnIZc8H8qU71G3CAuNAKefSVoy8uZ2Stg1KzYxpBb5hB5kuU8cpw=
  - secure: S+vJ6Tgqm23y5QDrpNrQiEOA90Hea6ny/M4FWnV85o2AR4wF5Y3vUpywYjx5gX7jzlaqdakc06WYJdXP9LV8yn/h1okwFbsc7LrZ+xLJcfzQ17eICgSC0oyPGCF5ASt95JJQ8htLknPXlkLo8MfMnGWIEsFvJEBmAC2jPKc6dwoveKHWThW1Spy3h27rAHDfE9PPvyZXBZXktfEDufsqbNKLAaOWTiUmFgC4jFdkcblqijKUlcGbYhEqaNEtIW5EBGzY4bXEzXj75h1pnnJgQIoXDhw/rC62k93DQOurOi6YWt1QPPbOBPGR8d/ikS6PpVac69jY1uuWCxqeg5cZqPephqflgdWqnOBVUekRLDWlk8jgOBTVnSYBxp3UiGcTDIGeW1P5uhBEhFW1pWWm0EzjP62nuRe7wyLVXltGKvFSrzjy7w6ikSpBYrBCWpx5Cpe9pSlrreQd0smHtLL4yjGh6SU4xoOk9VArZ9Hf2GsN2lifMrqXZVPZAuHEiHTjC+vr8JEmfAQ/ZnzxqjggUZ1DiJPs2LEmc0Fe6tH44YLw7mBBuTJb/TpbLZlmA8aq2YQ8T+9XfqkGshJkG4ZY578g6aN64EwE3JQk4PyfcyqeBJ6WkSRD/SF3E2G9FQtAh8DFq51uxPyu3F88i72WqTGq8BiaSXtvVnzHPWhNci0=
script:
- "./.travis/build.sh"
