version: '3.5'

services:

  #################################### KAFKA BROKER ####################################
  kafka:
    image: strimzi/example-kafka
    build: kafka-oauth-confluent/target
    container_name: kafka
    ports:
      - 9092:9092

      # javaagent debug port
      #- 5005:5005

    environment:

      # Java Debug
      #KAFKA_DEBUG: y
      #DEBUG_SUSPEND_FLAG: y

      #
      # KAFKA Configuration
      #

      KAFKA_OPTS: -Dzookeeper.sasl.client=false
      KAFKA_SUPER_USERS: User:admin

      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: CLIENT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: OAUTHBEARER
      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: OAUTHBEARER

      KAFKA_LISTENER_NAME_CLIENT_OAUTHBEARER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;"
      KAFKA_LISTENER_NAME_CLIENT_OAUTHBEARER_SASL_LOGIN_CALLBACK_HANDLER_CLASS: io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler
      KAFKA_LISTENER_NAME_CLIENT_OAUTHBEARER_SASL_SERVER_CALLBACK_HANDLER_CLASS: io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler

      KAFKA_AUTHORIZER_CLASS_NAME: io.strimzi.kafka.oauth.server.NoopAuthorizer

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1



      #
      # Strimzi OAuth Configuration
      #

      # Authentication config
      OAUTH_CLIENT_ID: "kafka-broker"
      OAUTH_CLIENT_SECRET: "kafka-broker-secret"
      OAUTH_TOKEN_ENDPOINT_URI: "http://${KEYCLOAK_IP:-keycloak}:8080/auth/realms/${REALM:-demo}/protocol/openid-connect/token"

      # Validation config
      OAUTH_JWKS_ENDPOINT_URI: "http://${KEYCLOAK_IP:-keycloak}:8080/auth/realms/${REALM:-demo}/protocol/openid-connect/certs"
      #OAUTH_INTROSPECTION_ENDPOINT_URI: "http://${KEYCLOAK_IP}:8080/auth/realms/${REALM:-demo}/protocol/openid-connect/token/introspect"
      OAUTH_VALID_ISSUER_URI: "http://${KEYCLOAK_IP:-keycloak}:8080/auth/realms/${REALM:-demo}"

      # For start.sh script to know where the keycloak is listening
      KEYCLOAK_IP: ${KEYCLOAK_IP:-keycloak}
      REALM: ${REALM:-demo}


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000