version: '3.5'

services:

  keycloak-import:
    image: strimzi/example-keycloak-import
    build: keycloak-import
    container_name: keycloak_import
    environment:
      KEYCLOAK_HOST: "${KEYCLOAK_HOST}"
